name: Main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: docker login -u jjno91 -p $CR_PAT ghcr.io
      - name: Build
        run: docker build -t ghcr.io/realmgame/terraform:latest terraform
      - name: Push
        run: docker push ghcr.io/realmgame/terraform:latest
