name: Main
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: echo $CR_PAT | docker login ghcr.io -u jjno91 --password-stdin
      - name: Build
        run: docker build -t ghcr.io/realmgame/terraform:latest terraform
      - name: Push
        run: docker push ghcr.io/realmgame/terraform:latest
